const PLANS = [
    {
        name: "iron",
        cpu: 100,
        node: "C-2",
        cpu_speed: 2.8,
        ram: 2048,
        disk: 20,
        price: 349,
        points: 1,
        description: "Ideal for hosting small Java servers or larger Bedrock servers.",
        players: 10,
    },
    {
        name: "gold",
        cpu: 200,
        node: "C-2",
        cpu_speed: 2.8,
        ram: 4096,
        disk: 40,
        price: 699,
        points: 2,
        description: "Advanced plan for mixed communities needing extensive resources.",
        players: 20,
    },
    {
        name: "redstone",
        cpu: 150,
        node: "H-3",
        cpu_speed: 3.7,
        ram: 4096,
        disk: 45,
        price: 777,
        points: 1,
        description: "High-performance plan tailored for resource-intensive communities.",
        players: 25,
    },
    {
        name: "lapiz",
        cpu: 250,
        node: "C-3",
        cpu_speed: 2.8,
        ram: 6144,
        disk: 65,
        price: 999,
        points: 1,
        description: "Optimized for diverse gameplay preferences in large communities.",
        players: 35,
    },
    {
        name: "diamond",
        cpu: 250,
        node: "H-3",
        cpu_speed: 3.7,
        ram: 8192,
        disk: 90,
        price: 1499,
        points: 2,
        description: "Optimized for diverse gameplay preferences in large communities.",
        players: 50,
    },
    {
        name: "netherite",
        cpu: 350,
        node: "H-3",
        cpu_speed: 3.7,
        ram: 12288,
        disk: 135,
        price: 2299,
        points: 3,
        description: "Top-tier plan for extensive communities requiring robust server resources.",
        players: 80,
    }
];

export { PLANS }